[build]
  command = "npm run build"
  publish = "dist"

# Optional: lock Node version to what you use locally
[build.environment]
  NODE_VERSION = "18"

# SPA redirect (use this OR public/_redirects, not both)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
